# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190608_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='documenturl',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
