# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-08 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
    ]
