# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-08 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='documenturl',
            field=models.URLField(max_length=250),
        ),
    ]
